#include<iostream>
using namespace std;
//Q : print the size of the datatypes which are commenly used in programs.
int main()
{
    cout<<"the size int : "<<sizeof(int)<<endl;
    cout<<"the size of char : "<<sizeof(char)<<endl;
    cout<<"the size of float : "<<sizeof(float)<<endl;
    cout<<"the size of double : "<<sizeof(double)<<endl;
    cout<<"the size of the short "<<sizeof(short)<<endl;
    cout<<"the size of bool : "<<sizeof(bool)<<endl;
    cout<<"the size of long : "<<sizeof(long)<<endl;
    cout<<"the size of long long : "<<sizeof(long long)<<endl;
    cout<<"the size of long double : "<<sizeof(long double)<<endl;


    return 0;
}